# Snowflake environment dependencies for Hotel Personalization Streamlit Dashboards
name: streamlit
channels:
  - snowflake
dependencies:
  - python=3.12
  - snowflake-snowpark-python
  - plotly
  - pandas
  - numpy
